# Generated by Django 3.0.8 on 2020-08-06 11:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='follower',
            field=models.ManyToManyField(related_name='userFollowing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='followers',
            name='following',
            field=models.ManyToManyField(related_name='userFollower', to=settings.AUTH_USER_MODEL),
        ),
    ]
